name: flauncher
description: Flutter-based Android TV launcher.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.7.5

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^11.6.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_remote_config: ^5.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  drift: ^2.5.0
  path_provider: ^2.0.13
  package_info_plus: ^8.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  sqlite3_flutter_libs: ^0.5.13
  unsplash_client: ^3.0.0
  webview_flutter: ^4.0.5
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  lints: ^6.0.0
  mockito: ^5.3.2
  drift_dev: ^2.5.2
  network_image_mock: ^2.1.1
  transparent_image: ^2.0.1
  package_info_plus_platform_interface: ^3.2.0
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/
